### ISSUE TITLE
Add splash screen

### ISSUE THREAD

**Issue by alexhorn** [neuland-ingolstadt/neuland.app#100]
https://blog.expo.dev/enabling-ios-splash-screens-for-progressive-web-apps-34f06f096e5c

**Comment by alexhorn** [comment]
Implementation temporarily reverted due to broken app icons

**Comment by M4GNV5** [comment]
Did you try removing and then adding the PWA from/to your homescreen? The manifest.json setup looks fine, the only difference is it not having a 64x64 pixel icon :thinking:

**Comment by alexhorn** [comment]
Yes, both app icons and splash screens were missing on our server

**Comment by M4GNV5** [comment]
Hmm then maybe the docker build script was broken. I can have a look into this.
