### ISSUE TITLE
Improve new food page UI

### ISSUE THREAD

**Issue by alexhorn** [neuland-ingolstadt/neuland.app#110]
Follow-up for #101

**Comment by M4GNV5** [comment]
Now it doesnt look that ugly anymore, but i am not sure if its a good / better user experience to have it in the overflow menu.

Should we just close this issue or ask someone with UXD expertise for a solution?

**Comment by Kaazyra** [comment]
![Bildschirmfoto 2022-02-09 um 18 25 50](https://user-images.githubusercontent.com/82609263/153256718-60af00d4-9166-496b-9512-56677dedeb74.png)
Hi, this is a sketch about how it could look like. There is a "Filter" to show the different meals
We could add sticker for the "Anmerkungen" like "Vegan, Rind, Vegetarisch, ..." 
What du you think about?
