### ISSUE TITLE
Show exam dates in chronological order (most recent first)

### ISSUE THREAD

**Issue by Curryking31** [neuland-ingolstadt/neuland.app#113]
It would be nice to have the exam dates displayed in the order they are scheduled.

**Comment by M4GNV5** [comment]
I don't think this is hard to implement, you simply have to sort [the examlist here](https://github.com/neuland-ingolstadt/neuland.app/blob/develop/rogue-thi-app/pages/calendar.js#L68-L69) based on `entry.date`.

Unfortunately neither @alexhorn nor myself have enough exams this year to implement and test this. Maybe you can do that @Curryking3 and send a PR or just push it directly?

**Comment by Curryking31** [comment]
Hey, thanks for replying! 

Unortunetly I am really busy with the exams atm but I will have a look on it after I finished them. For now the Exam wich I have already done is still in the app so I think the dates will still be online a few weeks after the exams.

**Comment by Curryking31** [comment]
I solved the problem with the chronically order in pullrequest #117

**Comment by alexhorn** [comment]
Fixed in #117.
