### ISSUE TITLE
Add Bathroom indicators for project pilot AK Kostenlose Menstruationsprodukte

### ISSUE THREAD

**Issue by Supernova1750** [neuland-ingolstadt/neuland.app#119]
Add indications (e.g. colored outlines) to a few bathrooms on the map. The bathrooms in question are: The one in the Library (if possible), C073, D171

**Comment by alexhorn** [comment]
Which toilet in the library do you mean? The one in the basement next to the lockers and book scanners?

**Comment by alexhorn** [comment]
Partially implemented in d6ce94c2c799e239864e4beabbc174dfae49d13b.

**Comment by M4GNV5** [comment]
fixed in 8ca043f1deb21451a27c445b2c3734dc5f735f27 (forgot to add the `closes #119` text to the commit)
