### ISSUE TITLE
Add week view to calendar

### ISSUE THREAD

**Issue by Supernova1750** [neuland-ingolstadt/neuland.app#121]
Add a week view in the timetable so users can get a better overview of their week.

**Comment by alexhorn** [comment]
Related to issue #20, we should possibly reevaluate how it can be done

**Comment by alexhorn** [comment]
Could possibly be implemented with [react-big-calendar](https://github.com/jquense/react-big-calendar) or [dayz](https://github.com/nathanstitt/dayz)

**Comment by Kaazyra** [comment]
Add A Tabbar where you can switch in the Timetable for the lessens from List to weekly calender view (like Google and co)

**Comment by alexhorn** [comment]
One person suggested adding a month view similar to TimeTree: https://pin.it/6GJwa3P

**Comment by Robert27** [comment]
Available in Neuland Next and intended as a native exclusive feature
