### ISSUE TITLE
API Error at INVG (Bus Timetable)

### ISSUE THREAD

**Issue by Robert27** [neuland-ingolstadt/neuland.app#125]
Opening the bus schedule results in the following error message:

```Fehler beim Abruf! API returned an error: "Unexpected/Malformed response from the INVG backend!"```

**Comment by M4GNV5** [comment]
The INVG API currently seems to return an error: https://www.invg.de/rt/getRealtimeData.action?stopPoint=2&station=IN-THoScu&sid=413

for me gives `{ error: true }` (not even a valid JSON lol)

**Comment by Robert27** [comment]
The INVG API is now working again, so the bug is fixed and the issue can be closed.
