### ISSUE TITLE
Missing app icon when adding to home screen

### ISSUE THREAD

**Issue by Robert27** [neuland-ingolstadt/neuland.app#126]
Adding the web app to the iOS home screen results in the following app icon.
However, if the app is saved as a bookmark in browser (iOS 15.4 / Safari), then the proper icon is used.

Android has not been tested.

![image](https://user-images.githubusercontent.com/53063597/159699274-3cb45152-ade8-4d7e-9a4f-37ba442621c3.png)

**Comment by Robert27** [comment]
I just tested it with the Xcode simulator, the problem occurs with iOS 15.4 on all devices.
I will test it again later with other iOS versions.

**Comment by M4GNV5** [comment]
Indeed after updating to iOS 15.4 i have the same problem. According to the links you sent we just need to [update our icon `purpose` in the manifest to `any`](https://github.com/neuland-ingolstadt/neuland.app/blob/develop/rogue-thi-app/public/manifest.json#L21)
