### ISSUE TITLE
Notification for student council election 

### ISSUE THREAD

**Issue by Supernova1750** [neuland-ingolstadt/neuland.app#128]
Create a notification to promote the student council election. The next election period is `21/06/2022 - 23/06/2022`. It can be similar to the discord and install prompt but it shouldn't be removable. It should probably appear a few days before the election and contain information about how and where to vote ( maybe clicking on it opens a new page with more info ).

**Comment by alexhorn** [comment]
This is related to issue #73, but way easier to implement

**Comment by alexhorn** [comment]
This was fixed in 52550efba071d58905c21ba29abd2d3b7d6fac4a, c795bff58d4eb98877fb971b967ccc074bd98e7d and 005aed66ae9f721160f05ad941ae6b669f3043d9.
