### ISSUE TITLE
Unreadeble text in Dark Mode

### ISSUE THREAD

**Issue by LukasW352435** [neuland-ingolstadt/neuland.app#129]
In Dark Mode you can't read the roomnumber of a class if selected.

![index](https://user-images.githubusercontent.com/37829455/161429742-e14f7488-cbef-4678-b854-8817a32f8b04.jpg)

**Comment by M4GNV5** [comment]
Can we use CSS to set link colors to something different when inside a hovered-highlighted container? Or should we just pick a different color for one of them?
