### ISSUE TITLE
Building J is missing in the roomplan

### ISSUE THREAD

**Issue by M4GNV5** [neuland-ingolstadt/neuland.app#131]
The new building J is missing both in the room map and in the room search.

**Comment by FabianSimonGross** [comment]
this extends to Bulding BN - N stands for Neuburg (soon AN and CN i think) and as Building S (Staufenbergstraße) maybe also Carissma at Marie-Curie (Outdoor-Testing Range)

**Comment by alexhorn** [comment]
Any solutions for this? Do we hope the THI updates their geo server or do we map them ourselves?
@FabianSimonGross Is there any chance we can get official floor plans?

**Comment by FabianSimonGross** [comment]
There would be a way. But that doesn't work. Just send an Mail to TuG or maybe I'm going to ask the Chancellor of THI.
