### ISSUE TITLE
Add native application screenshots into fastlane structure

### ISSUE THREAD

**Issue by CrsiX** [neuland-ingolstadt/neuland.app#134]
In order to promote the application in the respective playstores for native mobile apps, screenshots of the application are an absolute requirement. Therefore, I would suggest to add some screenshots showing different functionalities, menus, themes, ... of the app.

Those screenshots must be in PNG or JPG format and must be placed in `fastlane/metadata/android/en-US/images/phoneScreenshots`.  I highly suggest to use a high resolution for those images, since viewing them in fullscreen on a mobile device is crappy otherwise. Additionally, it would be nice to have them ordered lexicographical, since they get sorted by alphabet in the store page.

**Comment by Robert27** [comment]
Apple recommends using different screenshots depending on the device type (iPhone (with notch), iPad, Macbook), preferably with frames or annotations. So can this be achieved by using this method? Or will we only use this for Android?

**Comment by CrsiX** [comment]
I'm not sure how fastlane handles screenshots for iOS. Actually, its [documentation](https://docs.fastlane.tools/getting-started/ios/screenshots/) recommends to completely automate the creation of screenshots (same for Android, by the way). While I definitively understand the coolness of automated screenshot creation, it seems like a bit of overkill.

I guess this technique will be limited to Android, for now. But after we have the first bunch of screenshots, we may manually tweak them for different device types and generally adapt to the way Apple wants it to be.

**Comment by Robert27** [comment]
I have just tested it, the automatic creation with frameworks is basically not a problem, however we will probably have to write various native SwiftUITests to ensure the creation. I would therefore classify it as rather low in priority, also I have no experience so far for with tests for capacitor apps.

What does work is the automation of the publishing process, but that's not really an extra effort with Xcode. Unless you publish Android and iOS at the same time from one Mac…

**Comment by Robert27** [comment]
Neuland Next Feature
