### ISSUE TITLE
Switch to Ingolstadt API for parking lot occupancy

### ISSUE THREAD

**Issue by Robert27** [neuland-ingolstadt/neuland.app#139]
The city of Ingolstadt offers an access restricted API to display the parking data, I think it's the same data as on their website but then we would get along without scraping￼.

We should definitely think about switching to it, also for the full native app versions in the future.

[Open Data Ingolstadt](https://www.ingolstadt.de/Service/Weitere-Themen/Open-Data/)

**Comment by M4GNV5** [comment]
I've just contacted the parken@ingolstadt.de address. As of easter holidays I do not expect a response before 25.04. though.

**Comment by Robert27** [comment]
After a month, is there any news on using the API? Otherwise we can close the issue and continue using our previous solution.

**Comment by M4GNV5** [comment]
Ahh yes, we did receive the credentials for the Parking API on 2022-04-20. Sorry for not mentioning it here. I dont really want to share these credentials here, but if anyone wants to work on this feature feel free to contact me and i will hand them over.

**Comment by BuildmodeOne** [comment]
As we removed the mobility functionality as discussed in #425 this issue is now irrelevant.
