### ISSUE TITLE
Demo account for App Store verification

### ISSUE THREAD

**Issue by Robert27** [neuland-ingolstadt/neuland.app#140]
In order to publish the app in the App Store, it has to be controlled by the respective provider.
To ensure this, it is necessary that we provide login data.
Therefore, we should contact THI to request such a demo account.
Such an account might also be useful for internal testing and automation purposes.

**Comment by Robert27** [comment]
@FabianSimonGross You got the account by now or? If so, we can close this issue.

**Comment by FabianSimonGross** [comment]
We got the Account. @alexhorn and @M4GNV5 have it.
