### ISSUE TITLE
Automatically scrape semester dates from website

### ISSUE THREAD

**Issue by alexhorn** [neuland-ingolstadt/neuland.app#146]
We should automatically scrape semester dates from the PDF provided on the THI website.

https://www.thi.de/studium/pruefung/semestertermine/

**Comment by FabianSimonGross** [comment]
Shouldn't we ask if they might wanna introduce iCal Files with the PDF's? That would make this a lot easier. And it shouldn't be a huge problem because Profs already use an iCal File like this afaik.

**Comment by alexhorn** [comment]
Yes, this would be a lot better. Maybe we should argue that this would reduce the kind of mistakes that we had last semester.

**Comment by FabianSimonGross** [comment]
I'm just gonna send a request to the Chancellor of THI, let's see what happens.

**Comment by FabianSimonGross** [comment]
SCS answered they will not do that....

Soooouuuu we have to live with the pdf.

**Comment by OverloaderV** [comment]
I'll see if I can write a little cli utility that can scrape a pdf and parse it to a json
