### ISSUE TITLE
Show exact time at section mobility (New feature)

### ISSUE THREAD

**Issue by LukasW352435** [neuland-ingolstadt/neuland.app#148]
When looking at the mobility tab, you can see the time until the next train starts (see picture).

It would be nice to see the exact time too.
Example train starts at 10:30 o'clock.

![Screenshot_2022-06-01_13-30-03](https://user-images.githubusercontent.com/37829455/171394052-7963bf96-e7b1-450c-a072-d769b6f84f4d.png)

**Comment by Robert27** [comment]
I think we can link this suggestion with the implementation of this issue #137 .
Although it would be enough to adjust our train / bus API. Eventually we should add a toggle to the train / bus view to avoid overloading the UI.
