### ISSUE TITLE
Integrate pride components into default theme 

### ISSUE THREAD

**Issue by Robert27** [neuland-ingolstadt/neuland.app#149]
As suggested by @WebFreak001, we should consider integrating a Pride theme into the mostly used default mode during pride month.

Here we can rely on a more subtle design. In addition, possible adjustments with light and dark mode must be taken into account.

_Originally posted by @WebFreak001 in https://github.com/neuland-ingolstadt/neuland.app/issues/144#issuecomment-1144093211_

**Comment by M4GNV5** [comment]
Its live on [dev](https://dev.neuland.app/), i guess i forgot the "we can rely on a more subtle design" part :smile: 

Should we put it on master like this?

**Comment by Robert27** [comment]
Wow, this is a brilliant implementation. I really like the solution with the transparent background at the text and buttons area. Also the switch that is activated by default. Only the button corners look a bit unprofessional, but I don't know if you can fix that.

![C9CCD844-BA50-4F7E-AFE0-B3A212029C57](https://user-images.githubusercontent.com/53063597/171987104-5d306dcb-f34b-4678-8142-469b09cdad80.jpeg)

**Comment by Robert27** [comment]
We should think about offering this as a permanent variant for the standard theme after June or directly as a separate theme, as suggested in #144.

**Comment by alexhorn** [comment]
I think something that is enabled by default should be a lot more subtle than this

**Comment by alexhorn** [comment]
Implemented more subtle rainbow in d93e78202c3af88a662b596ec5a152ebacf79b52

**Comment by Robert27** [comment]
👌We want to display only the 6 basic colors and not the progress flag right? Or is there a plan to redesign the standalone Pride theme (#144)

**Comment by M4GNV5** [comment]
Looks cool i guess we can close this issue, but i strongly disagree with the Pride theme now. We should base it off the dark theme variant :stuck_out_tongue_closed_eyes:
