### ISSUE TITLE
Add location filter in room selection

### ISSUE THREAD

**Issue by Supernova1750** [neuland-ingolstadt/neuland.app#150]
There should be an option in the room finder to filter out rooms from certain locations (e.g. Neuburg Campus, Ingolstadt Campus)

**Comment by M4GNV5** [comment]
I do not think Neuburg is currently shown at all? At least I do not see rooms starting with `NE` in neither the building selection dropdown nor in the result list

**Comment by alexhorn** [comment]
Neuburg is `BN`, right? Maybe we should handle those separately, since they are shown when you search for building `B`

**Comment by Robert27** [comment]
Yes, Neuburg is `BN`, since their timetable for all lectures and modules is completely limited to the building. So we should definitely distinguish `B` and `BN`.
