### ISSUE TITLE
Remove THI Events from this calender view.

### ISSUE THREAD

**Issue by FabianSimonGross** [neuland-ingolstadt/neuland.app#156]
https://github.com/neuland-ingolstadt/neuland.app/blob/7b2813fdd91cedfc23bab53496702c1c315d954a/rogue-thi-app/pages/calendar.js#L57

In using the App last Semester we realized that the THI Events are just not interesting for Students. Those Events are more Interesting for externals and the App isn't designed to be used by externals.

**Comment by alexhorn** [comment]
Agreed, in theory it's a cool feature but most of the events aren't interesting to students and just detract attention from the Campus Life events
