### ISSUE TITLE
Introduce External Login

### ISSUE THREAD

**Issue by FabianSimonGross** [neuland-ingolstadt/neuland.app#157]
For External persons interested into our project there isn't any way to check it out. It might be an idea to create a Dummy Login with Dummy Data so externals (e.g. other Universitys and other students councils) can check it out.

Idea from OTH App. They do have an external Login so people can use Campus Navigation, Events Overview, Room Search and Mensa Components

**Comment by alexhorn** [comment]
Some of the functionality can already be used without login (`/food` and `/rooms`), but currently there's no way to get there except via a direct link.

**Comment by FabianSimonGross** [comment]
How about we introduce a View which is logged in by a Button on the Mainpage like "Log In as External User"

**Comment by alexhorn** [comment]
Issue was closed because I mistook it for #156, oops.

**Comment by alexhorn** [comment]
Added in c17e71738c8f705386993139c3f32dabde2b601c.
