### ISSUE TITLE
Provide Timetable data without using the THI App API

### ISSUE THREAD

**Issue by M4GNV5** [neuland-ingolstadt/neuland.app#162]
In order to provide timetable data without accessing the THI App API and allowing to use the timetable functionality in (semi-)guest mode we can use the primuss iCal functionality.
Primuss allows to download iCal data for each course of study via a predefined URL. The URL looks like this:

```
https://www3.primuss.de/stpl/index.php?FH=fhin&Language=de&mode=ical&Session=<session>User=<username>&sem=43&type=1&typeid=<course>
```

The `course` is a number, you can try different numbers to find diferent courses. I have not yet found an beginning and end. The `session` and `username` values are secrets which should be configurable. The server returns an iCal file. The filename includes the course name, the contents are the timetable for that course.

We have the following TODOs in order to turn this into a usable (semi)-guest timetable:

- [x] build a script which tries all `courseid`s, e.g. from 0 to 1000 and saves a courseid => course name mapping
- [ ] build an API to fetch all course names
- [ ] build an API to fetch iCal files for given course names (with caching)
- [ ] optional: add an option to filter iCal files to only include specific lectures
- [ ] build an UI to pick courses
- [ ] build an UI to pick lectures
- [ ] build an UI that fetches iCals and displays them like we are doing right now with data from the THI App API

**Comment by DanielMehlber** [comment]
[find-courses.zip](https://github.com/neuland-ingolstadt/neuland.app/files/9578672/find-courses.zip)

A small python script `find-courses.py` to list all existing course-ids and write them to file.
Use `python find-courses.py --help` to see all available command line arguments. `username` and `session` are required.

**Comment by M4GNV5** [comment]
Awesome work. The response includes a HTTP header which looks like this:
```
Content-Disposition: attachment; filename=WS2022_INF1.ics
```

We need to also save this filename, as it includes the name of the course of study we are interested in.
Then we can include this script as a build step in our [multistage docker file](https://github.com/neuland-ingolstadt/neuland.app/blob/develop/Dockerfile)

**Comment by DanielMehlber** [comment]
> Awesome work. The response includes a HTTP header which looks like this:
> 
> ```
> Content-Disposition: attachment; filename=WS2022_INF1.ics
> ```
> 
> We need to also save this filename, as it includes the name of the course of study we are interested in. Then we can include this script as a build step in our [multistage docker file](https://github.com/neuland-ingolstadt/neuland.app/blob/develop/Dockerfile)

In which format would you like to get the output? JSON?

**Comment by alexhorn** [comment]
> We need to also save this filename, as it includes the name of the course of study we are interested in. Then we can include this script as a build step in our [multistage docker file](https://github.com/neuland-ingolstadt/neuland.app/blob/develop/Dockerfile)

I think we should fetch the timetables dynamically during runtime. They change frequently, for example when classes get cancelled. If we did it during build time, we would need to rebuild every couple of days to fetch the current data.

**Comment by M4GNV5** [comment]
> > We need to also save this filename, as it includes the name of the course of study we are interested in. Then we can include this script as a build step in our [multistage docker file](https://github.com/neuland-ingolstadt/neuland.app/blob/develop/Dockerfile)
> 
> I think we should fetch the timetables dynamically during runtime. They change frequently, for example when classes get cancelled. If we did it during build time, we would need to rebuild every couple of days to fetch the current data.

The timetable data yes, but not the list of courses. This changes once per semester at most.

**Comment by M4GNV5** [comment]
Thank you again for the script @DanielMehlber. I changed some variable names and made the `main` simpler, but its now in the repo.

With that out of the way the course-list-API should be easy. The iCal fetching maybe not as much. Single course is easy, but having a single URL which returns multiple courses combined and filtered requires a good iCal library for nodejs to parse / combine / filter and generate the iCal entries.
The goal here is not to return a custom JSON format, but valid iCal, so the URL can also be added to your calendar software

**Comment by Robert27** [comment]
Stale because we have to wait for the official API for legal reasons.
