### ISSUE TITLE
Authenticate users via E-Mail

### ISSUE THREAD

**Issue by M4GNV5** [neuland-ingolstadt/neuland.app#163]
With the forced removal of the THI App API we do not know wether a user is actually part of the THI community. Features like #162 provide somewhat internal data and should not necessarily be public to the world.
We need to implement an user authentication flow, which checks a user is actually part of the THI community by sending a verification link to a @thi.de or @carissma.eu E-Mail.

This issue has the following TODOs:
- [ ] build an API that takes an E-Mail, validates it ends with @thi.de or @carissma.eu and sends a verification link with an included JWT to it while preventing spamming via the API
- [ ] build an UI to request a verification E-Mail
- [ ] build an UI to take the JWT from a verification link and save it to localStorage
- [ ] build a utility for API endpoints to easily require a verified user (e.g. for use in #162)

**Comment by alexhorn** [comment]
Maybe we could use an off-the-shelf authentication solution like [Logto](https://github.com/logto-io/logto) or [Keycloak](https://www.keycloak.org/). This way we would not have to build our own login system and could just plug it into our app using OAuth.

**Comment by M4GNV5** [comment]
I like the OAuth approach. The THI started using Azure AD as a 2FA enabled login provider. In the long run we could aim at authenticating users via THIs official login flow

**Comment by Robert27** [comment]
Stale because we have to wait for the official API for legal reasons.
