### ISSUE TITLE
Text overflow in Retro Theme at Mobility Card (see img)

### ISSUE THREAD

**Issue by FabianSimonGross** [neuland-ingolstadt/neuland.app#177]
![Bildschirmfoto vom 2023-02-02 15-35-02](https://user-images.githubusercontent.com/81598210/216353620-79621562-836a-4d95-aa54-470686e8381e.png)

**Comment by OverloaderV** [comment]
What happens in other themes? is there a line break in the word or does a different font make the word shorter?

**Comment by Robert27** [comment]
References neuland-ingolstadt/neuland.app-ios#5

**Comment by alexhorn** [comment]
> What happens in other themes? is there a line break in the word or does a different font make the word shorter?

With the default theme, the characters all fit inside the card since the font is smaller and the word is truncated after 20 characters.

**Comment by OverloaderV** [comment]
So what would need to be done is to figure out how many letters at most fit inside with the retro theme, then, if the retro theme is selected, truncate after that amount of letters programmatically? Or is there some sort of css rule that could be used to auto truncate?

**Comment by OverloaderV** [comment]
Furthermore, is this the only possible place this could happen or are there more places/situations to check

**Comment by OverloaderV** [comment]
I found another case of overflow on the actual mobility page ![Screenshot_20230203-100649.png](https://user-images.githubusercontent.com/22007229/216559126-03909d43-1ef4-4fd0-937a-27d3bf2f3e25.png)
