### ISSUE TITLE
Add Building K (Ingolstadt), Bn (Neuburg), 20 (Neuburg) to the room plan.

### ISSUE THREAD

**Issue by FabianSimonGross** [neuland-ingolstadt/neuland.app#179]
I'm trying to organize via StudVer the floor plans for the buldings.

After getting these we would need to do the same  as in #131

**Comment by Robert27** [comment]
Hopefully we can add the room plans before the semester starts.
Also, we must not forget to add building K in the advanced room search. https://github.com/neuland-ingolstadt/neuland.app/blob/2391a0569206e3744f90ffc732180a2c73affede/rogue-thi-app/pages/rooms/search.js#L24

**Comment by FabianSimonGross** [comment]
https://cloud.studverthi.de/s/D3jLm5cgbaWJK5i

Die Raumpläne als PDF sind hier. Es müsste nur jemand die ganzen Gebäude nachzeichnen.

**Comment by FabianSimonGross** [comment]
I should add K has higher priority than Neuburg I think. Due the fact, that Neuburg also knows where their rooms are and it's a smaller Campus

**Comment by alexhorn** [comment]
I did building J using QGIS by screenshotting the plans and tracing them using the [Freehand raster georeferencer](https://plugins.qgis.org/plugins/FreehandRasterGeoreferencer/) plugin.

**Comment by FabianSimonGross** [comment]
Building Bn and Cn (Neuburg are done) @alexhorn has the files.

**Comment by alexhorn** [comment]
First and second floor of building K are done as well. I will do the third and fourth floor later.

**Comment by FabianSimonGross** [comment]
I did all the openstreetmap stuff for Neuburg. I'd say these updates are more than enough.

Now the question persists for me: Do we want to implement, that a user is automatically shown the closest campi and a button to switch? Or how do we deal with that?

**Comment by alexhorn** [comment]
Maybe just center the map on Neuburg if the user belongs to the NI faculty and center it in Ingolstadt in all other cases?

**Comment by FabianSimonGross** [comment]
This is completed. Centering of the map is referenced in issue #209

**Comment by Robert27** [comment]
> First and second floor of building K are done as well. I will do the third and fourth floor later.

Any updates on this? Or any volunteers? ;)

**Comment by Robert27** [comment]
We have received the plans from Fabi, but we added so far only EG and 1. floor. The floors 2 and 3 of the K building are still missing.@M4GNV5

**Comment by M4GNV5** [comment]
Ohh, i didnt see the text you cited in your original comment, sorry. Maybe I should change my display brighness settings to be able to see grey text on black background :eyes:
