### ISSUE TITLE
Locked out of settings

### ISSUE THREAD

**Issue by alexhorn** [neuland-ingolstadt/neuland.app#186]
Since the dashboard settings are on the profile page, it is possible to lock oneself out of accessing the settings dialog. If you go into the settings, remove the profile page from the dashboard and then leave the profile page, there is no way to access the settings.

**Comment by alexhorn** [comment]
Also, if you log in as a guest you can not access the settings at all.

**Comment by Robert27** [comment]
Why don't we just add the settings icon again in the top right corner. Maybe a gear icon or even the profile of the user (initials with colored background etc.)
