### ISSUE TITLE
Bring back the restaurant name

### ISSUE THREAD

**Issue by M4GNV5** [neuland-ingolstadt/neuland.app#200]
Since #188 there is no way of knowing where to buy the listed meals. When having both Reimanns and Mensa selected we should display the restaurant somewhere alongside the meal.

![image](https://user-images.githubusercontent.com/5504713/223199161-031a6d4e-ebfc-4c2a-9899-7ae753aa4b3f.png)

**Comment by alexhorn** [comment]
@Kaazyra suggested splitting each day into two sections for the different restaurants

**Comment by Robert27** [comment]
Also, the "For students" seems a bit redundant to me. In the design concept with the pictures suitable, but here less.

**Comment by Robert27** [comment]
Now the restaurant selection is broken, if I deselect Reimanns it is still displayed. If I select only Reimanns then you see nothing at all.

**Comment by M4GNV5** [comment]
@Robert27 you were right. Fixed in 93c23c712d7d98826af9c81f92a553f5087f56ed
