### ISSUE TITLE
Bring back subtle pride-header. 

### ISSUE THREAD

**Issue by McBaumwolle** [neuland-ingolstadt/neuland.app#207]
Please bring back the previous page-header with some subtle colors, the current (new one) is just text and (in my opinion) **not enough** as a page-logo - almost looks boring. 

![image](https://user-images.githubusercontent.com/67203883/224509518-c9c4ebfb-b255-41c7-bf7f-7b39e917c970.png)

Basically undo https://github.com/neuland-ingolstadt/neuland.app/commit/fe800fac6c308503539c521f5ebdaf28f3bc01c9.

**Comment by BuildmodeOne** [comment]
Slay💅

**Comment by M4GNV5** [comment]
I changed it to have the pride raindbow only during pride month in fe800fac6c308503539c521f5ebdaf28f3bc01c9.
@alexhorn and I discussed wether we should make it blue/yellow (Ukraine flag colors).
Other options would be all THI-blue or all neuland violet?

We could have an emoji vote or something:

:tada: 
![image](https://user-images.githubusercontent.com/5504713/224510758-8ceaa897-e975-4ae1-ad05-43f0cf3bda16.png)

:rocket:
![image](https://user-images.githubusercontent.com/5504713/224510638-a177bea6-3592-45cf-ab1f-2f4891195509.png)

:laughing: 
![image](https://user-images.githubusercontent.com/5504713/224510723-bd011bfa-77a7-49fa-a303-f457ae5369ee.png)

:eyes:
![image](https://user-images.githubusercontent.com/5504713/224510702-a4cdd110-7180-4828-81c9-4311a1d1ce49.png)

**Comment by Robert27** [comment]
I would suggest that we rework the Pride theme and make it more simple (default with modifications).
This is where we could permanently integrate the rainbow line. 

Nevertheless I would keep the temporary overwrite of the default theme during Pride month.

**Comment by alexhorn** [comment]
I would leave this up to @Kaazyra since I don't know whether this fits into the new design they have developed

**Comment by Kaazyra** [comment]
I personally would prefer to add our new logo (+ lettering maybe, but logo alone would be cool too), so only the text Neuland.app. that would be in dark green in light mode and in white in dark. However, me and @alexhorn have discussed this before and we had different opinions. 
What would you find better? 
Neuland.app so or our Neuland logo.

**Comment by McBaumwolle** [comment]
Personally I prefer neuland.app to the e.V. logo because they are two different things, but I am not the one to judge - so I guess another vote would be helpful. 😌

**Comment by FabianSimonGross** [comment]
Why not use only the icon from the e.V. Logo. It would bring in consistency while being a good standalone.

**Comment by M4GNV5** [comment]
As discussed in the Signal group we will go with a linear version of :heart: and maybe bring the full logo in the future with a larger redesign.

![image](https://user-images.githubusercontent.com/5504713/224643530-26c424a6-8ae1-43d8-ac1a-71b851b429f5.png)
