### ISSUE TITLE
Changing Dashboard Editing Page 

### ISSUE THREAD

**Issue by Kaazyra** [neuland-ingolstadt/neuland.app#218]
Some Changes to the Page, where you can edit the Widgets of the Dashboard:
Add an X an a + instead of the trash can
Drag and drop for changing the dashboard card order

**Comment by M4GNV5** [comment]
Changing the icons should be easy, but if i recall correctly we had some issues with dragndrop. Especially on mobile phones where its not clear wether a drag action or a scroll is started.

**Comment by Robert27** [comment]
Closed due to limitation in the web environment. However, implemented in Neuland Next.
