### ISSUE TITLE
Wrong display of current week in food.js

### ISSUE THREAD

**Issue by Robert27** [neuland-ingolstadt/neuland.app#225]
I simulated that there are only three days available at Mensa, like it is the case before vacations. The day selector in food.js now shows Sunday as the first day.
In the second example I removed just the data for Thursday.

I think we should always display one week (Mo-Fr) and add error messages for missing days, like "no menu available".
So continue to disable the past days entirely, but make missing days clickable with an appropriate error message. 

However we could also, as suggested [here](https://github.com/neuland-ingolstadt/neuland.app/pull/210#discussion_r1142351656), still display the past days. But this would require an update of our API and all other applications (Mensa Widget etc.).

<img width="175" alt="Screenshot 2023-03-21 at 12 03 08" src="https://user-images.githubusercontent.com/53063597/226588695-064ad067-d260-4953-a695-ac4fae191dae.png">
<img width="175" alt="Screenshot 2023-03-21 at 12 13 21" src="https://user-images.githubusercontent.com/53063597/226590079-9118b1dc-2712-4465-b152-a48a64e1baee.png">

**Comment by BuildmodeOne** [comment]
![Screenshot_2023-03-22-07-52-45-18_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://user-images.githubusercontent.com/39560569/226824886-ae8b127d-7306-4daf-939a-eb37da1db031.jpg)

Additional bug: Wrong filler days (even though tested and fixed in #224)

**Comment by M4GNV5** [comment]
I just deployed it the dev app. #224 is live now.
This is also the reason why i created issue #226
