### ISSUE TITLE
Redundancy and clutter of map search options

### ISSUE THREAD

**Issue by Robert27** [neuland-ingolstadt/neuland.app#235]
Currently, we offer three different room searches in addition to the normal search.
Some of them are available as a link above the map, others in the DropDown menu. The suggestions are even present twice...
| | link | drop down |
|--------|--------|--------|
| hourly plan  | no | yes |
| period search  | yes | no |
| suggestions | yes | yes | 

We should display only one link between the search bar and the map. Hiding all options in the dropdown would make the functions too unattractive though.

We could display a link called "advanced search", where you can choose between the three search options (suggested by @alexhorn )

**Comment by BuildmodeOne** [comment]
Really good point. In my opinion the links and the kebab menu in general on the main room page should be revised. 

We should discuss that with the UXD Team.

**Comment by BuildmodeOne** [comment]
> We could display a link called "advanced search", where you can choose between the three search options (suggested by @alexhorn )

Showing _suggestions_ in "advanced _search_" is not really intuitive in my opinion

**Comment by alexhorn** [comment]
As a temporary solution I moved both links into a single line in 1503627f434d571f20c2ce085706df5632883eea.

**Comment by BuildmodeOne** [comment]
One idea would be to make the 'index' to the room page configurable. This means that the user can choose between the `map`, `search` and `suggestion` as the default page when pressing on the `Rooms` Tab.

<img src="https://user-images.githubusercontent.com/39560569/231393085-aa7bcff3-6181-461c-b06b-f428d87dbd32.png"  width="250">

This does obviously not solve the general problem but simplifies the navigation and enhances the user experience.

**Comment by FabianSimonGross** [comment]
Just realized this issue is linked with #209. So we should also think about how to implement Neuburg in this particular redesign.

**Comment by Robert27** [comment]
current implementation should be fine
