### ISSUE TITLE
Room occupancy not working or displaying correctly

### ISSUE THREAD

**Issue by McBaumwolle** [neuland-ingolstadt/neuland.app#236]
Sometimes the room search does not show accurate or right data about the occupancy of rooms, the example below is from 12:20.
![image](https://user-images.githubusercontent.com/67203883/233967112-146772dc-d38f-4957-9873-e774a3e3f22a.png)
![image](https://user-images.githubusercontent.com/67203883/233967124-1d8d0895-afa2-40a4-89c7-32cc96161a38.png)

And these are from last week, approx. 9am. 
![image](https://user-images.githubusercontent.com/67203883/233970826-9333544b-9b33-4b78-b5a8-f5d59070d317.png)
![image](https://user-images.githubusercontent.com/67203883/233970854-3633a864-5e83-432e-93e4-a4f5f0edfd58.png)

**Comment by M4GNV5** [comment]
I do not think this is a problem with our code. The room occupancy is directly taken from the THI API and I assume the error lies somewehere within their data?

**Comment by Robert27** [comment]
stale / wont't fix due to THI data source
