### ISSUE TITLE
Migrate to NextUI

### ISSUE THREAD

**Issue by FabianSimonGross** [neuland-ingolstadt/neuland.app#250]
Instead of migrating to Bootstrap 5 we could also migrate slowly to NextUI as discussed in the Neuland.App Workshop

Benefit of NextUI would be to get the new and cleaner Design in one full swoop.

As Reference NextUI Page.
https://nextui.org/

post scriptum: yes it is in beta buuut better design, also we're closing the bootstrap 5 issue #194  and replace it with this.

- [ ] 1. Components/cards #256 
- [ ] 2. Components/modale #257 
- [ ] 3. Components/page & Components misc #258 
- [ ] 4. Login / Profile / Food Page #259
- [ ] 5. Calender / Events #260 
- [ ] 6. Mobility / Library #261 
- [ ] 7. Grades / Lecturures #262 
- [ ] 8. Timetable / Rooms #263 
- [ ] 9. Dashboard  #264

**Comment by Robert27** [comment]
We could also use [Tamagui](https://tamagui.dev) instead. The framework also has a very modern design, is no longer beta and also has **React Native support**.

**Comment by FabianSimonGross** [comment]
Well I thought we'll get here.

The react native support is something we should actually consider therfore halt this for the moment and check what is a good way to go forward on this issue.

**Comment by Robert27** [comment]
closed as stale in favour of the react native version and more urgent issues
