### ISSUE TITLE
Move Backend and Backend-Utils to TypeScript 

### ISSUE THREAD

**Issue by FabianSimonGross** [neuland-ingolstadt/neuland.app#251]
In Order to complete issue #48 we discussed splitting up the issues so that smaller chunks can be completed by different people

The workflow we're thinking about is 

1. Update TypeScript Compilation
2. Backend/Backend-Utils
3. Fetch/Hooks/lib-stuff 
4. API 
5. Components 
6. Pages

**Comment by Robert27** [comment]
Most of the backend is already converted to TypeScript in [neuland-ingolstadt/neuland.app-native](https://github.com/neuland-ingolstadt/neuland.app-native). Therefore, most of the RN code can be reused.
Maybe we could even discuss a shared codebase between web and native.
