### ISSUE TITLE
Create i18 locale json files for Dashboard-Page

### ISSUE THREAD

**Issue by FabianSimonGross** [neuland-ingolstadt/neuland.app#274]
Referencing the top issue #96

- [x] 1. getServerSideProps in Dashboard-Page
---
German i18 locale file
- [x] 2. Locale File for Dashboard-Page
---
English i18 locale file
- [x] 3. Locale File for Dashboard-Page

**Comment by BuildmodeOne** [comment]
The modals in `rogue-thi-app\components\modal` still need to be translated :)
