### ISSUE TITLE
Improve english mensa API

### ISSUE THREAD

**Issue by Robert27** [neuland-ingolstadt/neuland.app#277]
Often, the English language version of the Mensa API is missing data, such as meal titles. Sometimes even different allergens are listed or missing.

In order to provide the most helpful information available, we should try to adapt our version of the API to handle these errors as best as possible. For example by filling in missing values with the German version, etc.

![Screenshot 2023-06-06 at 23 25 38](https://github.com/neuland-ingolstadt/neuland.app/assets/53063597/da7805de-a91a-4f83-bdd4-9814866ac97b)
erman version etc.

**Comment by BuildmodeOne** [comment]
One possibility would be to host [LibreTranslate](https://github.com/LibreTranslate/LibreTranslate) ourselves, for example, and then translate missing dishes via the German names.

**Comment by BuildmodeOne** [comment]
I think the best way to incorporate the allergens is to use the German API and map the allergens to English with a hardcoded list or something like that.
