### ISSUE TITLE
Library reservations not working 

### ISSUE THREAD

**Issue by BuildmodeOne** [neuland-ingolstadt/neuland.app#283]
**Describe the bug**
When reserving a seat in the library, and clicking on "Reservieren" currently nothing happens. In the new App it works, in the old one it doesn't. Maybe there were some changes to the backend.

**Comment by M4GNV5** [comment]
From what I've heard they had some discussions with the library and wanted to prevent multi-booking. Maybe they did change the API at some point during that rework.

**Comment by FabianSimonGross** [comment]
Yes they did @alexhorn and @M4GNV5 have a Mail with the current REST. The old one for library is not getting turned back on due to the double reservation problem they had.

**Comment by Robert27** [comment]
Yes, we also have the API documentation document. I think the implementation of the new API is the next big milestone for the coming weeks

**Comment by FabianSimonGross** [comment]
Yes indeed. I think so too, and the first thing to get back up and running would be the library
