### ISSUE TITLE
Exams: Classes shown twice and ECTS value wrong

### ISSUE THREAD

**Issue by Kaazyra** [neuland-ingolstadt/neuland.app#299]
**Describe the bug**
Some classes are shown twice and the ECTS have the value 0 but it should show 6 ECTS. 

**To Reproduce**
1. Go to Noten
2. Scroll down

![Screenshot_2023-07-06-08-32-30-611-edit_com android chrome](https://github.com/neuland-ingolstadt/neuland.app/assets/82609263/3e0cfec4-fcca-45fd-94be-e576ddd721ed)

**Comment by alexhorn** [comment]
The same bug appeared in the original THI-App. Can you check whether the migration to the new API fixed this in the dev version? (https://dev.neuland.app)

**Comment by Kaazyra** [comment]
No, ist not fixed.

**Comment by alexhorn** [comment]
Then its a problem with both APIs. I guess technically we could filter out identical entries in the client?
