### ISSUE TITLE
Add 1.0 THI API as fallback when 2.0 API is not working

### ISSUE THREAD

**Issue by BuildmodeOne** [neuland-ingolstadt/neuland.app#335]
When the 2.0 API is not working, we could add an automatic fallback to the previous, old API. 
This would of course be associated with high effort, but especially when the new API is down, bring a huge advantage for our users.

**Comment by M4GNV5** [comment]
I am not sure what legal implications this would have since the old API does not ask for an API key.
Also this would increase our js bundle size since we then would have to include our own TLS implementation again

**Comment by BuildmodeOne** [comment]
Since the legal situation of the use of the "old API" has not been clarified, this use should be avoided at an extreme.
