### ISSUE TITLE
Add shortcuts to PWA

### ISSUE THREAD

**Issue by BuildmodeOne** [neuland-ingolstadt/neuland.app#340]
A PWA allows you to add shortcuts which can be access from the Homescreen or can be added as Widgets. 
See [web.dev](https://web.dev/articles/app-shortcuts)

Example:
![image](https://github.com/neuland-ingolstadt/neuland.app/assets/39560569/7094eace-2efe-48fa-af76-b3181d7fb1d2)
[Source](https://www.heise.de/blog/Shortcuts-Schnellaktionen-und-Sprunglisteneintraege-fuer-Progressive-Web-Apps-4722790.html)

**Comment by M4GNV5** [comment]
https://caniuse.com/mdn-html_manifest_shortcuts

**Comment by BuildmodeOne** [comment]
> https://caniuse.com/mdn-html_manifest_shortcuts

🫠🫠🫠

**Comment by Robert27** [comment]
Available as exclusive Neuland Next Feature.
