### ISSUE TITLE
Update API Translations 

### ISSUE THREAD

**Issue by BuildmodeOne** [neuland-ingolstadt/neuland.app#366]
Due to the recent updates to the new geojson (thanks @Robert27), a lot of room functions are unnecessary and can be removed.

**Comment by Robert27** [comment]
`rooms_v2.4.geojson` is now available on the asset server.
Check out the react native implementation to easily integrate the changes here too.

https://github.com/neuland-ingolstadt/neuland.app-native/pull/51/files
