### ISSUE TITLE
Fix Reimanns API

### ISSUE THREAD

**Issue by Robert27** [neuland-ingolstadt/neuland.app#390]
With the latest change, the Reimanns API displays a hyphen in front of the title of the meal. Here the parser needs to be adjusted.

**Comment by Robert27** [comment]
e2894304491ba7fe49e5ad1956188aa69cf6e244

**Comment by M4GNV5** [comment]
did you force push to remove the console.log: c4edd559648c8b4b90e2402662b86efb5f298b62? :stuck_out_tongue: 

btw: you can mention issues in commit messages using :wink:

**Comment by Robert27** [comment]
Rip, I got caught 😂
But yeah, I know, I just forgot the issue even existed, but I'm not going to do a second push now.
