### ISSUE TITLE
Show notifications when a lecture is about to begin

### ISSUE THREAD

**Issue by alexhorn** [neuland-ingolstadt/neuland.app#55]

**Comment by M4GNV5** [comment]
Not sure how useful this is without #32. But having native phone notifications probably relies on apple push notifications / firebase cloud messaging (i assume?) and thus only works with a backend which has access to user data? Maybe we can implement this in coorperation with the THI in the future?

For now do we could only implement notifications for desktop users which keep the site open?

**Comment by M4GNV5** [comment]
https://stackoverflow.com/questions/63819485/sending-push-notifications-to-ios-from-pwa

The Apple-Wallet based way looks interesting, but is iOS only

**Comment by M4GNV5** [comment]
There are various ways of sending push notifications to mobile devices, but there does not seem to be a privacy-friendly one. All of them require some backend service having access to users timetables.
Privacy is a key concept built into the neuland.app and we should not sacrifice it for a feature that is already available by adding the timetable iCal URL to your iOS/Google/... calendar app.
