### ISSUE TITLE
Moodle events disappear on monday

### ISSUE THREAD

**Issue by alexhorn** [neuland-ingolstadt/neuland.app#80]
Campus Life events are automatically deleted from moodle after the newsletter is sent on monday.

**Comment by M4GNV5** [comment]
How is this related to ea605d8bc74026fdd4c15e0889121c9518fc52df? Can we close this issue?

**Comment by alexhorn** [comment]
Fixed in 145851fc4d11f28277a154b9e2f6f029fed99e91.
